routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Auth::Routes();

Route::get('activity/{id}/delete', ['uses' => 'ActivityController@destroy', 'as' => 'activity.delete']);

Route::resource('activity', 'ActivityController');
Route::resource('status', 'StatusController');

Route::get('activity/{situation?}/{status?}', 'ActivityController@listFilter');

app/Activity.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Activity extends Model
{

    protected $table = 'activities';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'situation', 'status_id', 'description', 'startDate', 'finishDate'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        
    ];

    public function status()
    {
        return $this->belongsTo('App\Status');
    }

}

app/Status.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Status extends Model
{

    protected $table = 'status';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        
    ];

}

app/Http/Controllers/ActivityController.php
<?php

namespace App\Http\Controllers;

use App\Repositories\ActivityRepository as Repository;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\DB;

class ActivityController extends Controller
{

    public function __construct(Repository $repository){
        $this->repository = $repository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $activities = $this->repository->findAll();
        $status = DB::table('status')->get();
        return view('entrevista.listagem', compact('activities', 'status'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $status = DB::table('status')->get();
        return view('entrevista.cadastro', compact('status'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $response = $this->repository->save($request);

        return $response;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {   
        $activity = $this->repository->getById($id);
        $status = DB::table('status')->get();
        return view('entrevista.cadastro', compact('status', 'activity'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $response = $this->repository->update($request, $id);
        
        return $response;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $response = $this->repository->delete($id);
        
        return redirect()->route('activity.index');
    }

    public function listFilter($situation, $status){
        $activities = $this->repository->filterList($situation, $status);
        $status = DB::table('status')->get();
        return view('entrevista.listagem', compact('activities', 'status'));
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/StatusController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class StatusController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/entrevista/cadastro.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Cadastro de Usuario</div>
                <div class="panel-body">
                    <form class="form-horizontal col-md-12 form" id="form" name="form" data-idActivity="{{ isset($activity) ? $activity->id : '' }}">
                        {{--  {{ csrf_field() }}  --}}

                        <div class="form-group col-md-12">
                            <div class="form-group col-md-12">
                                <label for="name" class="col-md-2 control-label">Nome</label>

                                <div class="col-md-8">
                                    <input id="name" value="{{ (isset($activity)) ? $activity->name : '' }}" type="text" class="form-control" name="name" autofocus>
                                        <span class="help-block">
                                            <strong></strong>
                                        </span>
                                </div>
                            </div>
                            <div class="form-group col-md-12">
                                <label for="situation" class="col-md-2 control-label">Situação</label>

                                <div class="col-md-8">
                                    <select class="form-control" name="situation" id="situation">
                                        <option value="Ativo" {{ (isset( $activity )) ? (($activity->situation == 'Ativo') ? 'selected' : '')  : ''}}>Ativo</option>
                                        <option value="Inativo" {{ (isset( $activity )) ? (($activity->situation == 'Inativo') ? 'selected' : '')  : ''}}>Inativo</option>
                                    </select>          
                                </div>
                            </div>
                            <div class="form-group col-md-12" >
                                <label for="status_id" class="col-md-2 control-label">Status</label>

                                    <div class="col-md-8">
                                        <select class="form-control" name="status_id" id="status_id">
                                            @foreach($status as $stat)
                                                <option value="{{$stat->id}}" {{ (isset( $activity )) ? (($activity->status_id == $stat->id) ? 'selected' : '')  : ''}}>{{$stat->name}}</option>
                                            @endforeach
                                        </select>          
                                    </div>
                            </div>

                            <div class="form-group col-md-12" >
                                <label for="description" class="col-md-2 control-label">Descrição</label>

                                <div class="col-md-8">
                                    <textarea id="description" type="text" class="form-control" name="description" autofocus>{{(isset($activity)) ? $activity->description : '' }}</textarea>
                                        <span class="help-block">
                                            <strong></strong>
                                        </span>
                                </div>
                            </div>

                            <div class="form-group col-md-12">
                                <label for="startDate" class="col-md-2 control-label">Dat.Inicio</label>

                                <div class="col-md-8">
                                    <input id="startDate" type="text" value="{{(isset($activity)) ? $activity->startDate : '' }}" class="form-control datepicker" name="startDate">
                                        <span class="help-block">   
                                            <strong></strong>
                                        </span>
                                </div>
                            </div>

                            <div class="form-group col-md-12">
                                <label for="finishDate" class="col-md-2 control-label">Dat.Termino</label>

                                <div class="col-md-8">
                                    <input id="finishDate" type="text" value="{{(isset($activity)) ? $activity->finishDate : '' }}" class="form-control datepicker" name="finishDate">
                                        <span class="help-block">
                                            <strong></strong>
                                        </span>
                                </div>
                            </div>

                        </div>

                        <div class="form-group col-md-12">
                            <button type="submit" class="btn btn-primary">Cadastrar</button>
                            <a class="btn btn-danger" href="{{ url('/activity') }}">Cancelar</a>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
<script>
    $(function () {

        $(document).ready(function(){
            $("#startDate").datepicker({
                minDate: 0,
                dateFormat: "yy-mm-dd",
                onClose : function(){
                    $("#finishDate").datepicker("option", "minDate", $("#startDate").datepicker('getDate'))
                }
            });

            $("#finishDate").datepicker({
                minDate: 0,
                dateFormat: "yy-mm-dd",
                onClose : function(){
                    $("#startDate").datepicker("option", "maxDate", $("#finishDate").datepicker('getDate'))
                }
            });

            if($('#status_id').children("option").filter(":selected").text() != 'Concluído'){
                $( "#finishDate" ).rules( "add", {
                    required: true
                });
            }else{
                $( "#finishDate" ).rules( "remove", 'required');
            }

        });

        $('#status_id').on('change', function(){
            if($('#status_id').children("option").filter(":selected").text() != 'Concluído'){
                $( "#finishDate" ).rules( "add", {
                    required: true
                });
            }else{
                $( "#finishDate" ).rules( "remove", 'required');
            }
        }),

        $('#form').on('submit', function (e) {
            e.preventDefault();
            if (!$(this).valid()) return false;

            console.log($('#form').attr('data-idActivity'));

            if($('#form').attr('data-idActivity') != ''){
                $.ajax({
                    type: 'put',
                    url: '/activity/'+$('#form').attr('data-idActivity'),
                    data: $("#form").serialize(),
                    success: function (resp) {
                        alert('Registro alterado !!!');
                        window.location = "/activity";
                    }
                });
            }else{
                $.ajax({
                    type: 'post',
                    url: '/activity/',
                    data: $("#form").serialize(),
                    success: function (resp) {
                        alert('Cadastro efetuado !!!');
                        window.location = "/activity";
                    }
                });
            }
            
        });

        $("#form").validate({
            rules: {
                name: {
                    required: true,
                    maxlength: 255,
                },
                situation: {
                    required: true,
                },
                status_id: {
                    required: true,
                },
                description: {
                    required: true,
                    maxlength: 600,
                },
                startDate: {
                    required: true,
                },
            },
            messages: {
                name: "O campo nome é obrigatorio",
                description: "O campo descrição é obrigatorio",
                startDate: "O campo data de inicio é obrigatorio",
                situation: "O campo data situação é obrigatorio",
                finishDate: "O campo data termino é obrigatorio",
            },
        });
    });

</script>
@endsection

resources/views/entrevista/listagem.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Listagem de Atividades</div>

                <div class="panel-body">
                    <label for="name" class="col-md-2 control-label">Filtros: </label>
                    <div class="col-md-3">
                        <select class="form-control" name="situation" id="situation">
                            <option value="" disabled selected>Situação</option>
                            <option value="Ativo" {{ (isset( $activity )) ? (($activity->situation == 'Ativo') ? 'selected' : '')  : ''}}>Ativo</option>
                            <option value="Inativo" {{ (isset( $activity )) ? (($activity->situation == 'Inativo') ? 'selected' : '')  : ''}}>Inativo</option>
                        </select>          
                    </div>
                    <div class="col-md-4">  
                        <select class="form-control" name="status" id="status">
                            <option value="" disabled selected>Status</option>
                            @foreach($status as $stat)
                                <option value="{{$stat->id}}" {{ (isset( $activity )) ? (($activity->status_id == $stat->id) ? 'selected' : '')  : ''}}>{{$stat->name}}</option>
                            @endforeach
                        </select>          
                    </div>
                    <div class="col-md-2">
                        <a href="" id="filtrar" class="btn btn-primary" >Filtrar </a>
                    </div>
                    <table class="table">
                        <thead>
                            <tr>
                            <th>Nome</th>
                            <th>Situação</th>
                            <th>Status</th>
                            <th>Descrição</th>
                            <th>Dat.Inicio</th>
                            <th>Dat.Termino</th>
                            <th>Opções</th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach ($activities as $activity)
                            <tr class="{{ ($activity->status->name == 'Concluído') ? 'concluidoFundo' : ''}}">
                            <td>{{ $activity->name }}</td>
                            <td>{{ $activity->situation }}</td>
                            <td>{{ $activity->status->name }}</td>
                            <td>{{ $activity->description }}</td>
                            <td>{{ $activity->startDate }}</td>
                            <td>{{ $activity->finishDate }}</td>
                            <td>
                                <a href="{{ route('activity.edit', $activity->id) }}" class="btn btn-info {{ ($activity->status->name == 'Concluído') ? 'invisible' : ''}}" ><i class="fa fa-pencil-square-o"></i> </a>
                                {{--  <a href="{{ route('activity.delete', $activity->id) }}" class="btn btn-danger"><i class="fa fa-trash"></i> </a>  --}}
                            </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>

            <a href="{{ route('activity.create') }}" class="btn btn-success"><i class="fa fa-plus-circle"></i> Cadastrar </a>

        </div>
    </div>
</div>
@endsection

@section('scripts')
<script>
    $('#filtrar').on('click', function(e){
        e.preventDefault();
        var situation = $('#situation').val();
        var status = $('#status').val();
        if($('#situation').val() == null){
           situation = '0';
        }
        if($('#status').val() == null){
            status = '0';
        }

        window.location = '/activity/'+situation+'/'+status;
        
        
    });
    
</script>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Home Page</div>

                <div class="panel-body">
                    <li><a href="{{ url('/activity') }}">Cadastro de Atividades</a></li>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Projeto Entrevista</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/style.css') }}" rel="stylesheet">
    <link href="{{ asset('css/font-awesome-4.7.0//css/font-awesome.min.css')}}" rel="stylesheet">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        Projeto Entrevista
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                         {{--  <li><a href="{{ url('/user') }}">Cadastro de Usuarios</a></li>  --}}
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
    <script src="{{ asset('js/jquery-validation-1.17.0/dist/jquery.validate.js') }}"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    @yield('scripts')
</body>
</html>